import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./../context/UserContext";
import { QuizProvider } from "@/context/QuizContext";
import { EssayProvider } from "@/context/EssayContext";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assignment System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `!function(c, l, a, r, i, t, y) {
        a[c]("metadata", (function() {
          a[c]("set", "C_IS", "0")
        }), !1, !0);
        if (a[c].v || a[c].t) return a[c]("event", c, "dup." + i.projectId);
        a[c].t = !0,
        (t = l.createElement(r)).async = !0,
        t.src = "https://scripts.clarity.ms/0.8.30/clarity.js",
        (y = l.getElementsByTagName(r)[0]).parentNode.insertBefore(t, y),
        a[c]("start", i),
        a[c].q.unshift(a[c].q.pop()),
        a[c]("set", "C_IS", "0")
      }("clarity", document, window, "script", {
        "projectId": "tflhyejrmb",  // Your project ID
        "upload": "https://y.clarity.ms/collect",  // Matches MO's endpoint
        "expire": 365,
        "cookies": ["_uetmsclkid", "_uetvid"],  // Optional: For MS Ads integration if needed
        "track": true,
        "content": true,
        "dob": 2093  // Optional: Age gate placeholder (set to future year for adults)
      });`,
          }}
        />

      </head>
      <body className={inter.className}>
        <UserProvider>
          <QuizProvider>
            <EssayProvider>
              {children}
              <Toaster position="top-center" richColors />
            </EssayProvider>
          </QuizProvider>
        </UserProvider>
      </body>
    </html>
  );
}